services:
  cubmaster:
    image: cubrid:11.2
    build: .
    hostname: ${STACK_NAME}_cubmaster
    environment:
      - CUBRID_COMPONENTS=MASTER
      - CUBRID_DB=hadb
      - CUBRID_DB_HOST=${STACK_NAME}_cubmaster:${STACK_NAME}_cubslave
    healthcheck:
      test: ["CMD", "gosu", "cubrid", "cubrid", "changemode", "$$CUBRID_DB@localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  cubslave:
    depends_on:
      - cubmaster
    image: cubrid:11.2
    hostname: ${STACK_NAME}_cubslave
    environment:
      - CUBRID_COMPONENTS=SLAVE
      - CUBRID_DB=hadb
      - CUBRID_DB_HOST=${STACK_NAME}_cubmaster:${STACK_NAME}_cubslave
    healthcheck:
      test: ["CMD", "gosu", "cubrid", "cubrid", "changemode", "$$CUBRID_DB@localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  cubbroker:
    depends_on:
      - cubmaster
      - cubslave
    image: cubrid:11.2
    environment:
      - CUBRID_COMPONENTS=BROKER
      - CUBRID_DB=hadb
      - CUBRID_DB_HOST=${STACK_NAME}_cubmaster:${STACK_NAME}_cubslave
    ports:
      - "40000:40000"
